# Generated by Django 4.0.3 on 2022-05-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_participant_meetup_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2022-05-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_emaill',
            field=models.EmailField(default='test@emailtes.com', max_length=254),
            preserve_default=False,
        ),
    ]
